- menu_name: "Services"

- name: "Contact Number"
  url: "/contact/"
  title: "Contact"

- name: "Instagram"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "Telegram"
  url: "/atom.xml"
  title: "Subscribe to Atom Feed"

- name: "Linkedin"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
